name: network_tracer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-190.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  mockito: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

scripts:
  rebuild: flutter pub run build_runner build --delete-conflicting-outputs
  win: flutter run -d windows
